### ISSUE TITLE
Add the command to the right click menu

### ISSUE THREAD

**Issue by H-G-Hristov** [fabiospampinato/vscode-open-in-terminal#6] opened 2021-01-27 08:44 UTC
I'd really love to have this command as a right click item in the Explorer.

It works great on Mac.

**Comment by fabiospampinato** [comment] 2021-04-01 21:10
I don't know it could be noisy 🤔

**Comment by fabiospampinato** [comment] 2021-04-02 16:38
Duplicate of #4

**Closed as completed by fabiospampinato** 2021-04-02 16:38 UTC
Labels: enhancement
