### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by 42060** [fabiospampinato/vscode-open-in-terminal#5] opened 2020-12-24 16:22 UTC
When I copy a code from GitHub into my macbook terminal it says -bash: https://github.com/la-deep-web/Phoneinfoga.git: No such file or directory .  Can anyone help?

**Comment by fabiospampinato** [comment] 2020-12-25 11:18
Can you provide precise steps for reproducing the issue?

**Comment by 42060** [comment] 2020-12-26 03:20
> Can you provide precise steps for reproducing the issue?
I'm sorry, I'm really new to this whole coding thing. I copy and paste the URL from the HTTPS clone into my terminal. Which looks  like this.  Bradens-MacBook-Pro:~ bradenblain$ https://github.com/sundowndev/PhoneInfoga.git
-bash: https://github.com/sundowndev/PhoneInfoga.git: No such file or directory

It always says "no such file or directory" no matter what clone from GitHub I use. It's not just Phoneinfoga.

I have python 3.9.1. That's all I know. Sorry if im not being clear. if you have a question just let me know.

**Comment by fabiospampinato** [comment] 2021-04-01 21:49
It may be related to #2, I'll have to take a closer look at that

**Comment by fabiospampinato** [comment] 2021-04-02 16:39
Duplicate of #2

**Closed as completed by fabiospampinato** 2021-04-02 16:39 UTC
Labels: needs more info
